### PR TITLE
feat: automatically profile when --require'd

### PR DESCRIPTION
**Pull request by ofrobots**

### CODE REVIEW

**Comment by ofrobots** [comment]
@nolanmar511 How do I get a link to the kokoro build status?

**Comment by aalexand** [comment]
@ofrobots http://fusion/dashboard/findbuilds?search_pattern=pprof-nodejs&project_types=&include_inactive_projects=false ?

**Comment by ofrobots** [comment]
Normally I see a link right here on the failed/passed status on GitHub, but there wasn't one. Secondly, following the link you pasted, I don't see a build corresponding to my PR.

**Comment by nolanmar511** [comment]
Yeah -- there aren't "details" links here. I'm still not sure why...

**Pull request merged**
